### ISSUE TITLE
Calling `AreaNFT.split` can give ownership of child tokens to an approver

### ISSUE THREAD

**Issue by markegli** [AreaWorld/ethereum-contracts#1]
the `split` function should use the owner, not `_msgSender()` when setting `_splitOwners[tokenId]` and emitting new `Transfer` events.

Assigning ownership to the message sender does not seem like expected behavior, and if `split` is called by an approved contract that doesn't expect to own the children, it can result in untransferable children tokens locked in the calling contract.

**Comment by fulldecent** [comment]
Thank you! This is a valid bug report.

At a minimum it is confusing for weird use cases, and at a maximum it is disastrous. Sorry, I don't have an immediate answer on rating/classification.

But either way this requires better documentation of the function to explain why it works that way and/or changing or reducing functionality so that dangerous things don't happen. So this is valid.

**Comment by fulldecent** [comment]
Thank you for your bug report! We worked on this at https://github.com/AreaWorld/ethereum-contracts/pull/7

Here are some notes on rating your finding.

IMPACT:

The function had advertised "The owner of an Area Token can irrevocably split...". While, yes, of course an operator already has permission to take your token, this function still exceeded its documented purpose.

Strictly speaking, this is a medium impact. "cause a function to fail or performs a wrong operation".  

LIKELIHOOD:

For this issue to cause the impact above, somebody would only need to perform the ERC721 setApprovalForAll from their account to some other externally owned account. This is a normal and supported operation.

Then the recipient would need to perform the split. They could do this using Etherscan, although this is not the normal website flow.

One of Medium likelihood or Low likelihood would be appropriate.

PAYOUT:

According to the bug bounty rules, this is an accepted problem with a risk rating of "medium severity" or "low severity". So let's round up and payout for medium. You win:

- Partial payout of the bug bounty (USD 1,000)
- This limited, first edition Area T-shirt, mailed to your house, in time for you to wear at NFT.nyc
- One Area NFT token from the token drop
- Public acknowledgement from the Area team and personally from the contract developer on Twitter (if you allow)

Please contact us privately at marcos@area.world email or on our Discord to @DappPunk#9999 to arrange these.
