### ISSUE TITLE
NFTMarketplace.sol - revokeBid

### ISSUE THREAD

**Issue by wallbeach** [AreaWorld/ethereum-contracts#4]
I'm not sure but in case of revoking the bid it should decrease the pending withdrawal and not increase the pending withdrawal:

`    function revokeBid(uint256 tokenId) external {
        require(msg.sender == tokenMarkets[tokenId].bidder, "Only the bidder may revoke their bid");
        _increasePendingWithdrawal(msg.sender, tokenMarkets[tokenId].lockedBid);
        _setBid(tokenId, address(0), 0);
    }`
 otherwise I can place a bid and revoke it and in both cases the pendingWithdrawal is increased..?

**Comment by fulldecent** [comment]
Thank you for sharing.

You are referring to this function: https://github.com/AreaWorld/ethereum-contracts/blob/4eb55b7a7f81f63caf54b6ee177ad5b017f762e2/contracts/NFTMarketplace.sol#L100

First, a brief discussion of how bidding starts. If you create bid then you have sent Ether to the contract to hold for you.

Now that you are revoking a bid, the expectation of the bidding party is that their original Ether will become available to withdraw. Therefore, in the `revokeBid` function it is appropriate to _increase_ the withdrawal available to the (former) bidder. So this is intended functionality.

---

P.S. In the "withdrawable" pattern, Ether is sent to parties by making it available to withdraw. Therefore the `Withdrawable` contract only supports _increasing_ withdraws from inheriting contracts. The sole way to decrease the pending withdrawal is for the external party to call `withdraw` to the their Ether.

`Withdrawable` contract: https://github.com/AreaWorld/ethereum-contracts/blob/4eb55b7a7f81f63caf54b6ee177ad5b017f762e2/contracts/Utilities/Withdrawable.sol
