### ISSUE TITLE
Where are the special instructions?

### ISSUE THREAD

**Issue by dtedesco1** [AreaWorld/ethereum-contracts#8]
https://github.com/LightArtists/area-ethereum-contracts/blob/60b280437268fe69aa11a254cb703f4fa21af66e/README.md?plain=1#L31

**Comment by fulldecent** [comment]
@dtedesco1 Previously Node was broken on M1 Macs, but it is fixed now.

Updated the README to reflect this, and ran the tests to confirm they are still passing.
